#!/bin/sh
# Start/stop the rma daemon.
#
### BEGIN INIT INFO
# Provides:          rma
# Required-Start:    $remote_fs $syslog $time
# Required-Stop:     $remote_fs $syslog $time
# Should-Start:      $network $named 
# Should-Stop:       $network $named 
# Default-Start:     2 3 4 5
# Default-Stop:	     0 1 6
# Short-Description: Regular background program processing daemon
# Description:       Hostmonitor RMA agent init script for debian
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DESC="rma daemon"
NAME=rma
DAEMON=/usr/sbin/rma/rma
PIDFILE=/var/run/rma.pid
SCRIPTNAME=/etc/init.d/"$NAME"
EXTRA_OPTS=" -d /usr/sbin/rma/rma.ini"

. /lib/lsb/init-functions

case "$1" in
start)  log_daemon_msg "Starting " "rma"
        start_daemon -p $PIDFILE $DAEMON $EXTRA_OPTS
		pidof $NAME > $PIDFILE
        log_end_msg $?
        ;;
stop)   log_daemon_msg "Stopping " "rma"
        killproc -p $PIDFILE $DAEMON
        RETVAL=$?
        [ $RETVAL -eq 0 ] && [ -e "$PIDFILE" ] && rm -f $PIDFILE
        log_end_msg $RETVAL
        ;;
restart) log_daemon_msg "Restarting " "rma"
        $0 stop
        $0 start
        ;;
status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;
*)      log_action_msg "Usage: /etc/init.d/rma {start|stop|status|restart}"
        exit 2
        ;;
esac

exit 0
